// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBillingSystem.Models;

namespace OnlineBillingSystem.Migrations
{
    [DbContext(typeof(OnlineBillingSystemDBContext))]
    [Migration("20210124120443_PaymentValidatorCreate")]
    partial class PaymentValidatorCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineBillingSystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentValidatorID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PaymentValidatorID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.PaymentValidator", b =>
                {
                    b.Property<int>("PaymentValidatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("PaymentValidatorID");

                    b.ToTable("PaymentValidators");
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.Payment", b =>
                {
                    b.HasOne("OnlineBillingSystem.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerID");

                    b.HasOne("OnlineBillingSystem.Models.PaymentValidator", "PaymentValidator")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentValidatorID");
                });
#pragma warning restore 612, 618
        }
    }
}
