// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBillingSystem.Models;

namespace OnlineBillingSystem.Migrations
{
    [DbContext(typeof(OnlineBillingSystemDBContext))]
    [Migration("20210124131530_InvoiceValidatorCreate")]
    partial class InvoiceValidatorCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineBillingSystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.InvoiceValidator", b =>
                {
                    b.Property<int>("InvoiceValidatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsValidInvoice")
                        .HasColumnType("bit");

                    b.HasKey("InvoiceValidatorID");

                    b.ToTable("InvoiceValidators");
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.InvoiceValidatorAndRuleValidator", b =>
                {
                    b.Property<int>("InvoiceValidatorAndRuleValidatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InvoiceValidatorID")
                        .HasColumnType("int");

                    b.Property<int>("ValidationRuleID")
                        .HasColumnType("int");

                    b.HasKey("InvoiceValidatorAndRuleValidatorID");

                    b.HasIndex("InvoiceValidatorID");

                    b.HasIndex("ValidationRuleID");

                    b.ToTable("InvoiceValidatorAndRuleValidators");
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentValidatorID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PaymentValidatorID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.PaymentValidator", b =>
                {
                    b.Property<int>("PaymentValidatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("PaymentValidatorID");

                    b.ToTable("PaymentValidators");
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.PaymentValidatorAndRule", b =>
                {
                    b.Property<int>("PaymentValidatorAndRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PaymentValidatorId")
                        .HasColumnType("int");

                    b.Property<int>("ValidationRuleId")
                        .HasColumnType("int");

                    b.HasKey("PaymentValidatorAndRuleId");

                    b.HasIndex("PaymentValidatorId");

                    b.HasIndex("ValidationRuleId");

                    b.ToTable("PaymentValidatorAndRules");
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.ValidationRule", b =>
                {
                    b.Property<int>("ValidationRuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ValidationRuleID");

                    b.ToTable("ValidationRules");
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.InvoiceValidatorAndRuleValidator", b =>
                {
                    b.HasOne("OnlineBillingSystem.Models.InvoiceValidator", "InvoiceValidator")
                        .WithMany("InvoiceValidatorAndRuleValidators")
                        .HasForeignKey("InvoiceValidatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBillingSystem.Models.ValidationRule", "ValidationRule")
                        .WithMany("InvoiceValidatorAndRuleValidators")
                        .HasForeignKey("ValidationRuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.Payment", b =>
                {
                    b.HasOne("OnlineBillingSystem.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerID");

                    b.HasOne("OnlineBillingSystem.Models.PaymentValidator", "PaymentValidator")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentValidatorID");
                });

            modelBuilder.Entity("OnlineBillingSystem.Models.PaymentValidatorAndRule", b =>
                {
                    b.HasOne("OnlineBillingSystem.Models.PaymentValidator", "PaymentValidator")
                        .WithMany("PaymentValidatorAndRules")
                        .HasForeignKey("PaymentValidatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBillingSystem.Models.ValidationRule", "ValidationRule")
                        .WithMany("PaymentValidatorAndRules")
                        .HasForeignKey("ValidationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
